/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PolicyManagement } from "./PolicyManagement";
export type { VehicleManagement } from "./VehicleManagement";
