/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PolicyManagement__factory } from "./PolicyManagement__factory";
export { VehicleManagement__factory } from "./VehicleManagement__factory";
