/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PolicyManagement } from "./PolicyManagement";
export type { VehicleManagement } from "./VehicleManagement";
export * as factories from "./factories";
export { PolicyManagement__factory } from "./factories/PolicyManagement__factory";
export { VehicleManagement__factory } from "./factories/VehicleManagement__factory";
